### ISSUE TITLE
Histskin disappears when interacting and receiving Blessings from Shrines.

### ISSUE THREAD

**Issue by ZidanReign** [NotTotal/Total-Skyrim-Overhaul#2]
Title says it all.

Mostly a reminder for Total.

Original discord message from myself: "Okay I found a weird interaction with histskin that other people have reported but I've found one way it can disappear.

When I went to riften forest start I went into the treehouse and blessed myself with the Kynareth shrine, when the blessing was up my histskin disappeared.  I cleansed myself with a potion and decided to go to solitude and check the rest of the shrines and the rest of the blessings also made histskin get removed until you cleansed the blessing."

**Comment by Redturtleee** [comment]
Is this site dead? Do you know another way to contakt the wabbajack team?
