### ISSUE TITLE
Failed Install for unable to find files or alternatives - Log included

### ISSUE THREAD

**Issue by jfranknichols** [NotTotal/Total-Skyrim-Overhaul#23]
Attempted to install TSO and had 3 files that could not be downloaded.  Numerous restarts failed with same errors.

20.12 - Downloading [full_inu] Medieval Knight Armor SSE.7z
20.12 - Downloading [full_inu] Galahad Renegade Coat SSE.7z
20.13 - Downloading [full_inu] Lord Nicholas Armor SSE.7z
20.8 - Hashed download is incorrect

21.14 - Trying to find solution to broken download for [full_inu] Galahad Renegade Coat SSE.7z
21.14 - Looking for generic upgrade for ok6HqrGQacs= (-3789338518710956382)
21.31 - Looking for generic upgrade for ok6HqrGQacs= (-3789338518710956382)
21.68 - No solution for broken download [full_inu] Galahad Renegade Coat SSE.7z GoogleDriveDownloader+State|1pRRSPyfHG71V3RyL3K1Z7cCuXnnHVfi8 could be found

24.37 - Trying to find solution to broken download for [full_inu] Medieval Knight Armor SSE.7z
24.38 - Looking for generic upgrade for jFukhihBJO0= (-1358889545245631604)
24.56 - Got a 521 from https://build.wabbajack.org/mod_upgrade/find/8c5ba486284124ed retrying in 608ms
25.34 - Looking for generic upgrade for jFukhihBJO0= (-1358889545245631604)
25.71 - No solution for broken download [full_inu] Medieval Knight Armor SSE.7z GoogleDriveDownloader+State|1nSs9FP1G-su2P_kOHBs2s0cVuR2WSKhJ could be found

36.3 - Trying to find solution to broken download for [full_inu] Lord Nicholas Armor SSE.7z
36.31 - Looking for generic upgrade for uLm1WwuICOw= (-1438750498580219464)
36.68 - Looking for generic upgrade for uLm1WwuICOw= (-1438750498580219464)
36.84 - No solution for broken download [full_inu] Lord Nicholas Armor SSE.7z GoogleDriveDownloader+State|1cL7BC2Nrvi2HTVv-ppZzyOkcszD5g7gA could be found

36.93 - Hashing Remaining Archives
36.93 - Looking for files to hash
37.19 - Found 884 total files, 867 matching filesize
37.79 - Unable to download [full_inu] Galahad Renegade Coat SSE.7z (GoogleDriveDownloader+State|1pRRSPyfHG71V3RyL3K1Z7cCuXnnHVfi8)

37.79 - Unable to download [full_inu] Lord Nicholas Armor SSE.7z (GoogleDriveDownloader+State|1cL7BC2Nrvi2HTVv-ppZzyOkcszD5g7gA)

37.8 - Unable to download [full_inu] Medieval Knight Armor SSE.7z (GoogleDriveDownloader+State|1nSs9FP1G-su2P_kOHBs2s0cVuR2WSKhJ)

37.8 - Cannot continue, was unable to download one or more archives

37.8 - File hash check (-42) f81906cd0ae6fdfd3c28e4c2d9b7bbc57c0c64b8a4a7c8714afb3d41ab7ee613
37.82 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
38.2 - File hash check (-42) f81906cd0ae6fdfd3c28e4c2d9b7bbc57c0c64b8a4a7c8714afb3d41ab7ee613

**Comment by tarkamacska1986** [comment]
[immyneedscake] FFXV Gentiana Shiva CBBE SSE SMP .7z
Broken archive.
