### ISSUE TITLE
LoversLab looks to be missing a mod maybe? 

### ISSUE THREAD

**Issue by NuclearWinter25** [NotTotal/Total-Skyrim-Overhaul#25]
![image](https://user-images.githubusercontent.com/108346413/176189086-5e6ac0e9-b6ca-4d3d-b51a-9110d726c0d0.png)

I keep coming across this a few minutes into the attempted install. 
Here is the last bit of my log as well if it provides any insights. I can post more if needed but character limit was reached. 

187 - Optimized 119316 directives to 119316 required
187.03 - Hashing Archives
187.03 - Looking for files to hash
187.05 - Found 43 total files, 27 matching filesize
254.69 - Downloading Missing Archives
254.69 - Missing 974 archives
254.69 - Getting Nexus API Key, if a browser appears, please accept
255.11 - Logged into the nexus as Ballerking2425
255.11 - Nexus calls remaining: 10000 daily, 500 hourly
255.36 - Logged into the nexus as Ballerking2425
255.36 - Nexus calls remaining: 10000 daily, 500 hourly
255.36 - Loading server whitelist
255.66 - Loaded permissions for 713 servers and 312 Google Drive files
255.67 - Getting upgrades list
256.03 - Downloading via proxy (4c9740bab841885d) https://drive.google.com/uc?id=1dNsBIaXPNlZWoNMPbPpMjBUfnS4eFUsy&export=download
256.03 - Downloading via proxy (b898c41c8b276475) https://drive.google.com/uc?id=1hoJxN_qq9pR2WbKYMTlibSIcfwA1-ze0&export=download
256.03 - Downloading via proxy (9438a9fa36e8defe) https://drive.google.com/uc?id=1CXe4llor7UO13v_t7NXY37dm73LojIfX&export=download
256.03 - Downloading via proxy (ccedb0c3b319c670) https://www.mediafire.com/file/xb9n38pajxt5z1h/Alder.7z/
256.03 - Downloading via proxy (b2f67da236115e56) https://www.mediafire.com/file/kyvjrap0vpjos67/Atanis.7z/
256.03 - Downloading via proxy (af127caa8d08244c) https://www.mediafire.com/file/re7godkupogdqdb/BDO_Ahon_Kirus_%255BSE%255D_-_CBBE_-_BHUNP.7z/
256.03 - Downloading via proxy (4fe3407cf026b1e6) https://www.mediafire.com/file/sc21i8303itjs21/BDO_Atanis_-_CBBE_SE_%2528Physics%2529.7z/
256.03 - Downloading via proxy (0914758561fa4cf0) https://www.mediafire.com/file/aeuxp4pp6j4a5ul/BDO_Berserker_-_CBBE_SE_%2528Physics%2529.7z/
256.03 - Downloading via proxy (bdea1a8d4f85b6ec) https://www.mediafire.com/file/jbm4287qkwtcbsf/BDO_Boss_Armor_01_-_CBBE_SE_%2528SMP%2529.7z/
256.03 - Downloading via proxy (46b269b758c85caa) https://www.mediafire.com/file/d1367rz51t1l6oo/BDO_India_%255BSE%255D_-_CBBE_-_BHUNP_-_%2528Physics_-_SMP%2529.7z/
256.03 - Downloading via proxy (cdd1190744476722) https://www.mediafire.com/file/agfgkyc9k5fbvh4/BDO_Ranger_Anemos_%255BSE%255D_-_CBBE_BodySlide_%2528SMP%2529.7z/
256.03 - Downloading via proxy (5276e754f5d7c901) https://www.mediafire.com/file/3ucd71wh3aap6i0/BDO_Ranger_La_Medellin_-_CBBE_SE_%2528SMP_-_Physics%2529.7z/
256.03 - Downloading via proxy (b5cbc53410701fca) https://www.mediafire.com/file/93l7kl2raszrtra/BDO_Valkyrie_SE_1-0-0.7z/
256.25 - Downloading via proxy (972a6f6e7b962f89) https://drive.google.com/uc?id=1G5yiU0xbXh_y9XsPDQ6z5Gg6razeb-Nk&export=download
256.4 - Downloading via proxy (46f06f387987bff1) https://drive.google.com/uc?id=1v1dc8jZnT4Xq6bB9Tt6XGaM8VnOFOpw8&export=download
256.4 - Downloading via proxy (aaa06eb54c7efdf1) https://www.mediafire.com/file/ogobg4v6b7lsfmy/BDOR_Eclipse_by_Team_TAL_fomod.7z/
256.4 - Downloading via proxy (a9c1f8a06d9d8eab) https://drive.google.com/uc?id=1aLukpnhO7YNorYl11VTy8-6HEEeFPP35&export=download
256.49 - Downloading via proxy (508a670a2d94d8df) https://drive.google.com/uc?id=1g0KQQqCDK_L-or_b0ow1usc0KdDK_WYR&export=download
256.49 - Downloading via proxy (2d4ffe9088140905) https://drive.google.com/uc?id=1HhKZwprqrh0w8ybw5NUROgderVA2IANY&export=download
256.49 - Downloading via proxy (f16cbf9c4611ea94) https://drive.google.com/uc?id=1KpTH4vEk1sf9QwLTG5K3k4Fps9AT3fJ0&export=download
256.63 - Downloading via proxy (4390ca82071fb227) https://drive.google.com/uc?id=1ZRN_2w1Vzh9o4-H9ymy5Au0P3NKApqwn&export=download
256.63 - Downloading via proxy (b217740d7fb3388a) https://drive.google.com/uc?id=1QrHV_lH3ESUSiN-4bYwrMivMr5YlQK-A&export=download
256.92 - Downloading via proxy (5e380efb68a8bd4c) https://drive.google.com/uc?id=1AU3j37pKA9IWYOnxBB9gXnrZOI1Qz6RS&export=download
257.06 - Downloading via proxy (5b13ad4b17e2d077) https://www.mediafire.com/file/hn0ivyx4azp4us4/Black_Leather_Thief_CBBE_SE.7z/file
257.06 - Downloading via proxy (8a8cc70e77ee6603) https://www.mediafire.com/file/besv9xsb9x0de8h/Black_Talon_Special_Edition.7z/
257.06 - Downloading via proxy (3b5e79db1e7a7515) https://www.mediafire.com/file/7tfmoks76cz56t4/Bless_HV_0102.7z/
257.06 - Downloading via proxy (88f7a5b3bf18284e) https://www.mediafire.com/file/whzetlbl8n2meoq/Bless_HV_2004.7z/
257.06 - Downloading via proxy (f870e76eb535143e) https://www.mediafire.com/file/bg95cbykz9gzw1n/Bless_MD_0102.7z/
257.06 - Downloading via proxy (fb8c83f85c479270) https://www.mediafire.com/file/bb0czpq00pe4pz4/Bless_MD_0204.7z/
257.06 - Downloading via proxy (6e6368a32a74b1e2) https://www.mediafire.com/file/2d4zhxo5fysy6xc/Bless_MD_2003.7z/
257.06 - Downloading via proxy (a7be3b77aa5760c1) https://www.mediafire.com/file/ln4dogdyccttm2n/Bless_MD_2009.7z/
257.06 - Downloading via proxy (031e18849d451dd0) https://www.mediafire.com/file/01v9dqzdh99b3e1/Bless_MD_3002.7z/
257.06 - Downloading via proxy (226367be3ee146e1) https://www.mediafire.com/file/8kbjgyvj05mi78z/Bless_MS_0101.7z/
257.06 - Downloading via proxy (02e8b33548e219f1) https://www.mediafire.com/file/sfovn5hzm8eixu2/Bless_MS_0102.7z/
257.06 - Downloading via proxy (08b900e22f7de4b8) https://www.mediafire.com/file/4qvvga4lrptut9q/Bless_RB_3004.7z/
257.06 - Downloading via proxy (2f1de82d86b1821d) https://www.mediafire.com/file/dnnzh844zwdj95r/C5Kev%2527s_Herme_Mora_Priestess_CBBE_SE_fomod.7z/
257.06 - Downloading via proxy (9e6ca720ab6bbee8) https://www.mediafire.com/file/0li0x872uuwowvl/Dark_Disciple_%255BSE%255D_-_CBBE_-_BHUNP.7z/
257.06 - Downloading via proxy (2c10756cc868b95f) https://www.mediafire.com/file/pe0qh0grqv8nnqp/Dark_Souls_Regular_Knight.7z/
257.06 - Downloading via proxy (2fbc858d9cab3b5b) https://drive.google.com/uc?id=1bBhqwH969t1UBVAJVtOog9k2uKJQ-hjY&export=download
257.2 - Downloading via proxy (1ebd836e37c7733e) https://drive.google.com/uc?id=1Ck6NHy2ojNC8sU2qhg9H1oRHOtATiXjv&export=download
257.2 - Downloading via proxy (41d46f87f1a3eb9d) https://drive.google.com/uc?id=1r8kngKdDHKb9nIJQpWywhciBn4-Sirgy&export=download
257.84 - Downloading via proxy (618ad525e219031d) https://www.mediafire.com/file/ftrq4eywwn2bmjb/Dragon+Lilly+-Definitive+Edition-.7z/file
257.84 - Downloading via proxy (733172045de87e37) https://drive.google.com/uc?id=1NmCBtSPE9kFllbaggn0-gK6lo6KJ-y8w&export=download
257.84 - Downloading via proxy (6c517b04930f7fcf) https://drive.google.com/uc?id=1vfCLSqq2s14BtR0-Xbu5ysSGthwo-dAN&export=download
257.84 - Downloading via proxy (ad5f60efde5f8ec0) https://www.mediafire.com/file/134vdiza6u9mnm2/First_Summoner_Witch.7z/
257.84 - Downloading via proxy (b51caf8c23f2156a) https://drive.google.com/uc?id=13R4F59XHf3oZsESIGMrGRnbwbqlSULYN&export=download
257.84 - Downloading via proxy (599dcf5a29c25993) https://www.mediafire.com/file/vme3216ry9ml63s/Gatti_Jewel.7z/file
257.84 - Downloading via proxy (707fede5a3386a1f) https://www.mediafire.com/file/vav8pnnh2jpkbgk/Gatti_Misogi_Armor.7z/file
257.84 - Downloading via proxy (18f131ed02502659) https://drive.google.com/uc?id=1RV3qJsi72iFTj4ILDREwpxRbJVI99PQV&export=download
257.85 - Downloading via proxy (95a7613d571651f5) https://drive.google.com/uc?id=15_0njBUjHKidNnJPmLXEygzGVWsA3Zbq&export=download
257.85 - Downloading via proxy (e75517227134b0a5) https://www.mediafire.com/file/y7qbh72k4seaurb/Jingang_Outfit_2-0-0_SE.7z/
257.85 - Downloading via proxy (45e4343ed2f86bef) https://www.mediafire.com/file/cwh41xp46yzyk4i/Lady_Alina_Outfit_CBBE_SE_%2528Physics_-_CBBE_SMP_-_3BA%2529_fomod.7z/
257.85 - Downloading via proxy (0e448ee73aa3358e) https://www.mediafire.com/file/bu5cxbye4bvvvtz/Lightning_Archer_%255BSE%255D_-_CBBE_-_BHUNP.7z/
257.85 - Downloading via proxy (330d92b855b22f5f) https://www.mediafire.com/file/plu0tkvs7fmpmn9/MBO_0027_CBBE_SE_HDT-SMP.7z/
257.85 - Downloading via proxy (fb28200e2ae4075a) https://www.mediafire.com/file/odlvy4uyrd3us2k/MBO_0051_-_CBBE_SE_%2528Physics%2529.7z/
258.26 - Downloading via proxy (156193adcb78f213) https://drive.google.com/uc?id=1JoSeVzSBIa4YrbPNtrE6HNFLE4FoQ_wU&export=download
258.26 - Downloading via proxy (fedb135e42c408a6) https://www.mediafire.com/file/rsdw21ogf433uve/Paragon+Aurora+Glacier+Empress.7z/file
258.26 - Downloading via proxy (37e4262a58b2bdfe) https://www.mediafire.com/file/ulpbccm9m50xtkn/Paragon_Sparrow_Huntress.7z/file
258.26 - Downloading via proxy (8c24388f77cad531) https://www.mediafire.com/file/f9ekncasa8ddhus/Paragon+Sparrow+Rogue.7z/file
258.26 - Downloading via proxy (f66389bc54eb59e0) https://www.mediafire.com/file/4vv388x5hw3tf6y/Purple_Esmeralda_%255BSE%255D_-_CBBE_-_BHUNP.7z/
258.26 - Downloading via proxy (a192bb6f84058b0a) https://www.mediafire.com/file/q2v1o0zyd8htlt5/Ram_Horn_Witch_%255BSE%255D_-_CBBE_-_%2528Physics_-_SMP_-_3BA%2529.7z/
258.26 - Downloading via proxy (c83e1329c185fd03) https://www.mediafire.com/file/lcz0mjsf8fyrngy/Redguard+Royal+Armor.7z/file
258.26 - Downloading via proxy (15d048c660fd7966) https://www.mediafire.com/file/vlyb03viw5h66k1/(Royan)+Ryza.7z/file
258.26 - Downloading via proxy (c29c67b32b97addc) https://www.mediafire.com/file/8hqhmk9q439u6ql/Tara+[SE]+-+CBBE+-+BHUNP.7z/
258.26 - Downloading via proxy (404dc24958a92f89) https://drive.google.com/uc?id=1zx6pYunYVmbRw_G08ZIsKFxBUB5JnTNZ&export=download
258.26 - Downloading via proxy (2b7bc35c4821b0e9) https://www.mediafire.com/file/no6svg7y70cj0gx/Troll_Bone_Armor_CBBE_%2528Physics_-_CBBE_SMP_-_3BA%2529.7z/
258.26 - Downloading via proxy (704e1ff2e80acac8) https://drive.google.com/uc?id=1ffvswEcf6MghF-PbTFL85ZTWELgBQakq&export=download
258.26 - Downloading via proxy (57302525e0c1bbe0) https://www.mediafire.com/file/zpmysia7jxsuy3l/TsunTsun+Armor+Remastered+2.0.7z/file
258.26 - Downloading via proxy (4b4a0138be27c257) https://www.mediafire.com/file/lu0ey0bpk1xm83v/Valkyrie_Olympia_%255BSE%255D_-_CBBE_-_BHUNP.7z/
258.26 - Downloading via proxy (84e7f0d70abe30d0) https://www.mediafire.com/file/y9nkxcyro826w5y/Ves.7z/file
258.26 - Downloading via proxy (4056361ac68da223) https://www.mediafire.com/file/kxikwim3juhgzxd/Vindictus_Crystal_Rose_CBBE_SE_HDT-SMP_fomod.7z/
258.26 - Downloading via proxy (37bbaf55058bcdfc) https://www.mediafire.com/file/8xv30ezbg2g5gtp/Woodland_Priestess_SE.7z/
258.26 - Downloading via proxy (9e438f3074c72afa) https://www.mediafire.com/file/34xmdqdjf623naq/[Christine]+Adahy.7z/file
258.26 - Downloading via proxy (da09a99453010334) https://www.mediafire.com/file/2ntiawmf5yzoii4/%255BChristine%255D_Altmer_Archer.7z
258.26 - Downloading via proxy (5de782cf06939308) https://www.mediafire.com/file/45q12jkn68jgffs/[Christine]+Arathia.7z/file
258.27 - Downloading via proxy (4654cd0be788c151) https://www.mediafire.com/file/j7hzddlilnk6zc4/[Christine]+Assassin+Girl.7z/file
258.27 - Downloading via proxy (217d66db3ced07e0) https://www.mediafire.com/file/m6vcqryvl2yarb2/04_%255BChristine%255D_Bandit_Summoner.7z/file
258.27 - Downloading via proxy (8714c7ef4afc1eb1) https://www.mediafire.com/file/hsaj1v2hghpwst3/[Christine]+College+Warrior.7z/file
258.27 - Downloading via proxy (f689eeb432003af0) https://www.mediafire.com/file/fgoyj3pxkh9r9ui/%255BChristine%255D_Companion_Moon.7z/file
258.27 - Downloading via proxy (05600bbf6757fcdd) https://www.mediafire.com/file/t2jjzedv5ptphmn/[Christine]+Dragon+Berserkr+v4.7z/file
258.27 - Downloading via proxy (20bc36e623f5dd1c) https://www.mediafire.com/file/73ho5bkcn23xsnn/%255BChristine%255D_Dragon_Breaker.7z/
258.27 - Downloading via proxy (eea22e9f0cfe717b) https://www.mediafire.com/file/a829yjv6ikonqpq/[Christine]+Dragon+Fighter+v2.7z/file
258.27 - Downloading via proxy (035a53730adc43f9) https://www.mediafire.com/file/xxc1nqrinwoashv/[Christine]+Dragon+Guard.7z/file
258.27 - Downloading via proxy (e00ef961cd3ed641) https://www.mediafire.com/file/zc5p0x3lrhc5kz2/[Christine]+Dragon+Slaughter.7z/file
258.27 - Downloading via proxy (58297bd85c7d20b8) https://www.mediafire.com/file/4ke7032jzdo9s2c/%255BChristine%255D_Dragon_Veil.7z
258.27 - Downloading via proxy (40bcd1b37c7c5122) https://www.mediafire.com/file/h2ekbsae68fs7x6/[Christine]+Dragon+Viking.7z/file
258.27 - Downloading via proxy (3843b9e2826c0056) https://www.mediafire.com/file/ksom6obgomn6bmx/%255BChristine%255D_Earth_Warden_CBBE_%2528Physics_-_CBBE_SMP_-_3BA%2529_fomod.7z
258.27 - Downloading via proxy (874b5d52e8996014) https://www.mediafire.com/file/q6zsxkfzns30ivy/%255BChristine%255D_Eastern_Ronin_CBBE_%2528Physics_-_CBBE_SMP_-_3BA%2529_fomod.7z
258.27 - Downloading via proxy (727de1870ea64865) https://www.mediafire.com/file/ova7hrh4etntg7b/%255BChristine%255D_Eldergleam_Queen.7z/file
258.27 - Downloading via proxy (855ac1b924d7671f) https://www.mediafire.com/file/7x52vaws8aizs7x/%255BChristine%255D_Exnem_Demonic.7z/file
258.27 - Downloading via proxy (f57c40e9f4b05c09) https://www.mediafire.com/file/jhjb2pajwwi0out/%255BChristine%255D_Exnem_Witch.7z/file
258.27 - Downloading via proxy (cd542eea09a6bb73) https://www.mediafire.com/file/xuw4j9ks9hxk6yg/[Christine]+Farshadow+Ranger+2.0.7z/file
258.27 - Downloading via proxy (3c44cc0c1ac784cb) https://www.mediafire.com/file/0ugqz89nzkhwbcu/%255BChristine%255D_High_Queen.7z
258.27 - Downloading via proxy (613a1fb3b14f1bc5) https://www.mediafire.com/file/cn9jxly2unniocr/[Christine]+Hunterborn.7z/
258.27 - Downloading via proxy (4f783c0a1242e1a2) https://www.mediafire.com/file/m7hhasaq9pyvq8m/%255BChristine%255D_Keeper_of_the_Sun_CBBE_SE_fomod.7z/
258.27 - Downloading via proxy (4988ace7074aff0c) https://www.mediafire.com/file/b7le7dra0f1y1x7/DOA_-_Night_Parade_of_One_Hundred_Demons.7z/
258.27 - Downloading via proxy (0be0cd6d1ca63877) https://www.mediafire.com/file/nnutteyc53dfxnu/[Christine]+Ninian.7z/
258.27 - Downloading via proxy (cbcf3784633eb04b) https://www.mediafire.com/file/497egeshx0jjtjr/%255BChristine%255D_Nocturnal%2527s_Embrace_CBBE_%2528Physics_-_CBBE_SMP_-_3BA%2529_fomod.7z
258.27 - Downloading via proxy (8d36cc9a4c6791c0) https://www.mediafire.com/file/1adglyhf23wc0xe/[Christine]+Nomadic+Huntress.7z/file
258.27 - Downloading via proxy (05c068c27751de73) https://www.mediafire.com/file/24drp59wvfmshh0/[Christine]+Nord+Ascended.7z/file
258.27 - Downloading via proxy (96256f14850abb64) https://www.mediafire.com/file/qe2wlbhp7zpo7yq/[Christine]+Queen+Barbarian.7z/file
258.27 - Downloading via proxy (676606802a4d2f80) https://www.mediafire.com/file/isjyp6c6b939iul/
258.27 - Downloading via proxy (ae1f1ad3214ebd48) https://www.mediafire.com/file/2y24qz2ox4x67qo/%255BChristine%255D_Venom_Blade_Maiden_CBBE_SE_fomod.7z/
258.27 - Downloading via proxy (8230f20f437c1fa6) https://www.mediafire.com/file/gju4busg18b872f/%255BChristine%255D_Violet_Sorceress_Aphrodite_CBBE_SE_fomod.7z/
258.27 - Downloading via proxy (a0a5d2a751294174) https://www.mediafire.com/file/5wfke2vhtg5i46p/%255BChristine%255D_Wood_Warden.7z
258.27 - Downloading via proxy (6a0e33850f128257) https://www.mediafire.com/file/c038efag87cbx1k/%255BChristine%255D_Zhurong.7z
258.27 - Downloading via proxy (956ead6741891674) https://drive.google.com/uc?id=1wTR2XVRcC5Rl1YVyqUqd4_sRFuLXMmui&export=download
258.27 - Downloading via proxy (5934db3971622995) https://drive.google.com/uc?id=1YB6V09RCGMiHLy1zN045KBA7AA4tj6UK&export=download
258.42 - Downloading via proxy (218c090593879491) https://www.mediafire.com/file/369mq5q15b02sie/%255BDint999%255D_BDO_Striker_CBBE_SE_fomod.7z/
258.42 - Downloading via proxy (75c2aaaa774d54c1) https://drive.google.com/uc?id=1THN3jBMBTHydVWV_DeADu3AQCZEvYAKT&export=download
258.42 - Downloading via proxy (6be5c1aee0b3a6e1) https://drive.google.com/uc?id=15rXBnyE41ZHFztQ122G6XRlgPhtw8KZN&export=download
258.42 - Downloading via proxy (5d543c8cdf1977de) https://drive.google.com/uc?id=1pRRSPyfHG71V3RyL3K1Z7cCuXnnHVfi8&export=download
258.42 - Downloading via proxy (97a8f945247c02ec) https://drive.google.com/uc?id=1cL7BC2Nrvi2HTVv-ppZzyOkcszD5g7gA&export=download
258.42 - Downloading via proxy (dfb44dce4e3695df) https://drive.google.com/uc?id=1nSs9FP1G-su2P_kOHBs2s0cVuR2WSKhJ&export=download
318.56 - Downloading via proxy (b36ac6aae82d3598) https://mega.nz/file/EqZ2EQpb#dDi75Ix3W5zS_Ee7yOartTRi4_9zpfmrTYVwQKy5Mqg
318.88 - Downloading via proxy (34ae6116efdb5dde) https://mega.nz/file/srR0yIbZ#rsTaW12GjDuG8QW1HuPYlui4ja-gVmNC1WEmTP8iRgQ
319.13 - Downloading via proxy (7bd4472270666f79) https://mega.nz/file/xnYWwQxQ#zl7tNj9O1opkvDvOpSGGlDfz4wmjtW6A-VvQnFNpgRc
319.29 - Downloading via proxy (b1334b3a387f3e77) https://mega.nz/file/knQQhQZB#2CeI8ZpOeFCkJpf8Op6-hlzrdKd_eI_AmZtTOkeWRsc
319.54 - Downloading via proxy (d345c52c425a2d49) https://mega.nz/file/g7IwQYaI#uASe7NJ04jHQ1WYVOmET4TbG5iM8c-xz_c8GtISZz_c
319.72 - Downloading via proxy (07f597ce716416b8) https://mega.nz/file/F6ZhBaJT#XKdDnI5TqaNaMfYwM9K1_A29nP4iIN7UfjvKOxrWyj8
319.99 - Downloading via proxy (9248477cc892c841) https://mega.nz/file/87JHyKSZ#1EWVru3vSWZsknJDUVuFzwreC0Uw7pNffgT5kU5ZSOc
320.23 - Downloading via proxy (5d622bdde4cc5e84) https://mega.nz/file/QmB0kQLZ#DGzlAlvVFuS5SgwMY1SIZk84TAxUDmq-lL6eOQG2nQU
320.38 - Downloading via proxy (6bce259cc1ccadce) https://mega.nz/file/xzwQwQZa#lCD2KiMQuD7DAh7vToEjMv-7plMCNhluDHv7v-gXVhQ
320.39 - Downloading via proxy (7d2635637457f4cb) https://www.mediafire.com/file/c1qt8494p8uvn5y/%255BKirax%255D_Vindictus_Sakura_Blossom_CBBE_SE_HDT-SMP_fomod.7z/
320.39 - Downloading via proxy (e8cbe97817e514f3) https://www.mediafire.com/file/ta679dq9dpe9pcz/%255BMelodic%255D_Mistress_Lilith_CBBE_%2528Physics_-_CBBE_SMP_-_3BA%2529_fomod.7z/
320.48 - Downloading via proxy (307822f9fc2e6bb6) https://drive.google.com/uc?id=1iy9FT2kf8vq2g0aTOuFtlLNKiyUepfq9&export=download
320.48 - Downloading via proxy (f546dff5f94e9cbc) https://drive.google.com/uc?id=1u9Fvkc5xgY4vr3oiPZGkC_cX2CuwX2FV&export=download
320.91 - Downloading via proxy (2cab9b4052a8125b) https://drive.google.com/uc?id=1ssqZ7O28hB0MuDGBoQMSnqCSFUTbugAM&export=download
320.91 - Downloading via proxy (d71e4da6cdb5fd8f) https://drive.google.com/uc?id=1G-r_seDgTy5k-WzxpzzYk3OON9KFMQYd&export=download
321.07 - Downloading via proxy (30e4c2c08f91e6da) https://drive.google.com/uc?id=1qDN1OymReXzS52ZidrD4JywEgnpus-D5&export=download
321.07 - Downloading via proxy (4f07e0ae52d2abd5) https://drive.google.com/uc?id=1qBpFZmOIp6B_JmSXl7-FB4kLDeDeJxAf&export=download
321.07 - Downloading via proxy (e72321eaccdd1fa8) https://drive.google.com/uc?id=1w8FYON11jWnOY0J8yqaMxKUtEYuI6TdA&export=download
321.07 - Downloading via proxy (f20ae62e4d2b1cbe) https://drive.google.com/uc?id=1TkeHDdN48ybtTeRH5zpE9_cjKCGAgiHq&export=download
321.07 - Downloading via proxy (3f5e9bf6e7f075f3) https://drive.google.com/uc?id=1RgKwQ3KpZHgxP-CIjvXqleIGZcI5KH3l&export=download
321.23 - File hash check (-42) 884066303b4f613a018d3c4c4543104afeea572d0bb9416de4c12c3ab9b89569
321.33 - File hash check (-42) 884066303b4f613a018d3c4c4543104afeea572d0bb9416de4c12c3ab9b89569
321.39 - 
321.52 - File hash check (-42) 884066303b4f613a018d3c4c4543104afeea572d0bb9416de4c12c3ab9b89569
321.74 - File hash check (-42) 884066303b4f613a018d3c4c4543104afeea572d0bb9416de4c12c3ab9b89569

**Comment by Taylorsd** [comment]
I am having the same issue, but with the other file. I backtracked and downloaded the file manually and put it in the downloads folder but it's not being recognized. 

This is the file it is pointed to that I downloaded and put in my DL folder:
https://www.loverslab.com/files/file/16006-se-team-tals-dm-bdor-danharum-smp-3ba/?do=download&csrfKey=d6bfb8e17735b87c4386ca53f4236467

[SE] Team TAL's DM BDOR Danharum SMP 3BA 1.0.0

I was able to DL [SE] DM BDOR Caroxya by Team TAL

**Comment by Taylorsd** [comment]
So I just realized there were multiple Team Tal conversions to download from Lovers Lab, so I just manually downloaded all of them, and then it wasn't the Wabbajack didn't recognize the manual downloads, it was just I didn't download ALL of them. So it's working now. I don't want to see anything from Team Tal and Lovers Lab for a while :) 

To manually download the files copy and paste the URL and delete the end of the URL up to the /
