### ISSUE TITLE
Error during installation: "The system cannot find the file specified: [C:.........\actors\character\khajitmale]

### ISSUE THREAD

**Issue by jorundoa** [NotTotal/Total-Skyrim-Overhaul#6]
So I keep getting this error when trying to install TSO. I've deleted and redownloaded everything a few times (even verified game files in Skyrim SE). But the installation keeps stopping here. 
![bilde](https://user-images.githubusercontent.com/10432896/95024098-52861980-0681-11eb-8284-ecc469c54e49.png)

I'm uncertain which mod is in error. I've tried downloading High Poly Head 1.2 (SE) and put it in the downloads folder of wabbajack before I started the installation.

Any idea what might cause this?

**Comment by jorundoa** [comment]
Oh wait, I just noticed this, does that mean Windsong Immsersive Chacater Overhaul might be the culprit?

![bilde](https://user-images.githubusercontent.com/10432896/95024174-c0cadc00-0681-11eb-92b3-b38014e19da0.png)

**Comment by jorundoa** [comment]
I might mention that I installed from "Browse modlist" in Wabbajack, because I couldn't find out where I was supposed to download the file for "install from disk"

**Comment by gdzinke** [comment]
I ran into this issue as well. Same spot. I also installed from "browse modlist" in Wabbajack.

**Comment by jollld** [comment]
Me too. Havent found any way to fix this.

**Comment by jollld** [comment]
"In case anyone is having trouble with the 'Khajiit/handsmale_msn' (as Johnas above mentioned). Switching to the 2.2.2.0 version of Wabbajack as Total pinned resolves the issue. I simply switched version and resumed the original install no issues that I can see."
Apparently.

**Comment by gdzinke** [comment]
This worked for me thanks
